version: '2.1'
services:
  maria_db:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
    - ./mysql_database:/var/lib/mysql
    ports:
    - 3306:3306
    expose:
    - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - maria_db:db
    ports:
    - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: docker
  api:
    container_name: backend_api
    links:
    - maria_db:db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    depends_on:
    - maria_db
    command: bash -c "
      /app/relapp/start_python_server.sh"
