CREATE TABLE PERSON (
   ID INT IDENTITY NOT NULL PRIMARY KEY,
   FIRST_NAME VARCHAR(25),
   LAST_NAME VARCHAR(25)
   );
CREATE TABLE ADDRESS (
  ID INT IDENTITY NOT NULL PRIMARY KEY,
  STREET VARCHAR(55),
  CITY VARCHAR(55),
  STATE VARCHAR(5),
  POSTAL_CODE VARCHAR(10)
);
CREATE TABLE PERSON_ADDRESS_MAP (
  PERSON_ID INT NOT NULL,
  ADDRESS_ID INT NOT NULL
);